
version: "3.2"
services:

  sut:
    restart: always
    container_name: sut
    command : bash -c " 
                      python manage.py makemigrations &&
                      python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:8000"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"



